// <auto-generated />
using System;
using Accountancy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Accountancy.Migrations
{
    [DbContext(typeof(AccountancyContext))]
    [Migration("20200606172052_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Accountancy.Models.AccountancyInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BillCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HouseholdModelID")
                        .HasColumnType("int");

                    b.Property<double>("NetVal")
                        .HasColumnType("float");

                    b.Property<DateTime>("TimestampDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("HouseholdModelID");

                    b.ToTable("AccountancyInformation");
                });

            modelBuilder.Entity("Accountancy.Models.HouseholdModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("HouseholdModel");
                });

            modelBuilder.Entity("Accountancy.Models.AccountancyInfo", b =>
                {
                    b.HasOne("Accountancy.Models.HouseholdModel", null)
                        .WithMany("Invoices")
                        .HasForeignKey("HouseholdModelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
