apiVersion: v1
kind: PersistentVolume
metadata:
  name: accountancy-sql-db-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: accountancy-pd
    fsType: pd-standard
