apiVersion: v1
kind: Service
metadata:
  name: accountancy-sqlserver
  namespace: tecaisgrp3
spec:
  selector:
    app: accountancy-db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountancy-db
  namespace: tecaisgrp3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountancy-db
  template:
    metadata:
      labels:
        app: accountancy-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: pass1234
          volumeMounts:
            - name: accountancy-sql-vol
              mountPath: /var/opt/mssql
      volumes:
        - name: accountancy-sql-vol
          persistentVolumeClaim:
            claimName: accountancy-sql-db-pvc
