apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tecaisgrp3
  name: expenditure-measurement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expenditure-measurement
  template:
    metadata:
      labels:
        app: expenditure-measurement
    spec:
      containers:
        - name: expenditure-measurement-app
          image: mikkelbc/expenditure:v1
          ports:
            - containerPort: 80
