apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: status-sql-db-pvc
  namespace: tecaisgrp3
spec:
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: tecais-storage-class
