apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: itonk_tecais
  name: water-consumption-submission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: water-consumption-submission
  template:
    metadata:
      labels:
        app: water-consumption-submission
    spec:
      containers:
        - name: water-consumption-submission-container
          image: mikkelbc/water-consumption-submission:v1
          ports:
            - containerPort: 80
